#pragma once

#include "mlir/Bytecode/BytecodeOpInterface.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/Dialect.h"
#include "mlir/IR/OpDefinition.h"
#include "mlir/Interfaces/ControlFlowInterfaces.h"
#include "mlir/Interfaces/InferTypeOpInterface.h"
#include "mlir/Interfaces/SideEffectInterfaces.h"

#include "KunIr/KunIrDialect.h"
#include "KunIr/KunIrTypes.h"

// NativeOpTrait<"Name"> expands to ::mlir::OpTrait::Name in generated code,
// so the trait class must live in that namespace.  We prefix it with KunIr
// to avoid collisions with MLIR builtins.
namespace mlir {
namespace OpTrait {

/// Trait for element-wise kunir ts ops.
///
/// Provides a shared static inferReturnTypes that always yields
/// !kunir.ts<firstOperand.elemType, 1>.  Ops that carry InferTypeOpInterface
/// and this trait require no per-op inferReturnTypes definition.
template <typename ConcreteType>
class KunIrElemwiseTsResultType
    : public TraitBase<ConcreteType, KunIrElemwiseTsResultType> {
public:
  static mlir::LogicalResult inferReturnTypes(
      mlir::MLIRContext *ctx, std::optional<mlir::Location>,
      mlir::ValueRange operands, mlir::DictionaryAttr,
      mlir::PropertyRef, mlir::RegionRange,
      llvm::SmallVectorImpl<mlir::Type> &inferred) {
    auto inputTy = llvm::cast<::kunir::TsType>(operands[0].getType());
    inferred.push_back(
        ::kunir::TsType::get(ctx, inputTy.getElementType(), 1));
    return mlir::success();
  }
};

} // namespace OpTrait
} // namespace mlir

// Convenient alias in the kunir namespace.
namespace kunir {
namespace OpTrait {
template <typename ConcreteType>
using ElemwiseTsResultType =
    ::mlir::OpTrait::KunIrElemwiseTsResultType<ConcreteType>;
} // namespace OpTrait
} // namespace kunir

// Generated by TableGen
#define GET_OP_CLASSES
#include "KunIr/KunIrOps.h.inc"
