#pragma once

#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/Dialect.h"
#include "mlir/IR/OpDefinition.h"
#include "mlir/Interfaces/SideEffectInterfaces.h"

#include "KunGpu/KunGpuDialect.h"
#include "KunIr/KunIrTypes.h"

// Generated by TableGen
#define GET_OP_CLASSES
#include "KunGpu/KunGpuOps.h.inc"
